-- KRS Connect Phase 3 Migration + Sicherheits-Fixes (Migration 2/7, S2 2026-06-12)
-- FIX S2: UPDATE mit Alias (users.email band im Original an auth.users!)
ALTER TABLE posts ADD COLUMN IF NOT EXISTS is_pinned BOOLEAN DEFAULT FALSE;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS is_urgent BOOLEAN DEFAULT FALSE;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS image_url TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_url TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS auth_uid UUID;
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_auth_uid ON users(auth_uid) WHERE auth_uid IS NOT NULL;
UPDATE users u SET auth_uid = (SELECT au.id FROM auth.users au WHERE au.email = u.email) WHERE u.auth_uid IS NULL AND u.email IS NOT NULL;

CREATE TABLE IF NOT EXISTS reactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  target_type TEXT NOT NULL CHECK (target_type IN ('post', 'message')),
  target_id BIGINT NOT NULL,
  user_id BIGINT REFERENCES users(id),
  emoji TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (target_type, target_id, user_id, emoji)
);
ALTER TABLE reactions ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS post_reads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES users(id),
  read_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (post_id, user_id)
);
ALTER TABLE post_reads ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_post_reads_post ON post_reads(post_id);
CREATE INDEX IF NOT EXISTS idx_post_reads_user ON post_reads(user_id);

CREATE INDEX IF NOT EXISTS idx_posts_pinned ON posts(channel_id, is_pinned) WHERE is_pinned = true;
CREATE INDEX IF NOT EXISTS idx_reactions_target ON reactions(target_type, target_id);
CREATE INDEX IF NOT EXISTS idx_team_members_user ON team_members(user_id);
CREATE INDEX IF NOT EXISTS idx_team_members_team ON team_members(team_id);
CREATE INDEX IF NOT EXISTS idx_channels_team ON channels(team_id);
CREATE INDEX IF NOT EXISTS idx_posts_channel ON posts(channel_id);
CREATE INDEX IF NOT EXISTS idx_posts_parent ON posts(parent_id) WHERE parent_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_messages_conversation ON messages(conversation_id);
CREATE INDEX IF NOT EXISTS idx_conversation_members_user ON conversation_members(user_id);
CREATE INDEX IF NOT EXISTS idx_conversation_members_conv ON conversation_members(conversation_id);

CREATE OR REPLACE FUNCTION get_app_user_id()
RETURNS BIGINT
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT COALESCE(
    (SELECT id FROM users WHERE auth_uid = auth.uid() LIMIT 1),
    (SELECT id FROM users WHERE email = (SELECT email FROM auth.users WHERE id = auth.uid()) LIMIT 1)
  );
$$;

CREATE OR REPLACE FUNCTION toggle_reaction(
  p_target_type TEXT,
  p_target_id BIGINT,
  p_user_id BIGINT,
  p_emoji TEXT
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_exists BOOLEAN;
BEGIN
  SELECT EXISTS(
    SELECT 1 FROM reactions
    WHERE target_type = p_target_type
      AND target_id = p_target_id
      AND user_id = p_user_id
      AND emoji = p_emoji
  ) INTO v_exists;

  IF v_exists THEN
    DELETE FROM reactions
    WHERE target_type = p_target_type
      AND target_id = p_target_id
      AND user_id = p_user_id
      AND emoji = p_emoji;
  ELSE
    INSERT INTO reactions (target_type, target_id, user_id, emoji)
    VALUES (p_target_type, p_target_id, p_user_id, p_emoji);
  END IF;

  RETURN NOT v_exists;
END;
$$;

DO $$ BEGIN
  BEGIN DROP POLICY IF EXISTS "Allow all insert" ON conversation_members; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN DROP POLICY IF EXISTS "Allow all read" ON conversation_members; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN DROP POLICY IF EXISTS "Allow all update" ON conversation_members; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN DROP POLICY IF EXISTS "Allow all insert" ON conversations; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN DROP POLICY IF EXISTS "Allow all read" ON conversations; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN DROP POLICY IF EXISTS "Allow all update" ON conversations; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN DROP POLICY IF EXISTS "Allow all insert" ON messages; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN DROP POLICY IF EXISTS "Allow all read" ON messages; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN DROP POLICY IF EXISTS "Allow all insert" ON posts; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN DROP POLICY IF EXISTS "Allow all read" ON posts; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN DROP POLICY IF EXISTS "Allow all update" ON posts; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN DROP POLICY IF EXISTS "Allow all delete" ON posts; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN DROP POLICY IF EXISTS "Allow all read" ON reactions; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN DROP POLICY IF EXISTS "Allow all insert" ON reactions; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN DROP POLICY IF EXISTS "Allow all update" ON reactions; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN DROP POLICY IF EXISTS "Allow all delete" ON reactions; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN DROP POLICY IF EXISTS "Allow all update" ON users; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN DROP POLICY IF EXISTS "Allow all insert" ON team_members; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN DROP POLICY IF EXISTS "Allow all read" ON team_members; EXCEPTION WHEN OTHERS THEN NULL; END;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'conversation_members' AND policyname = 'cm_select_own') THEN
    CREATE POLICY "cm_select_own" ON conversation_members FOR SELECT
      USING (user_id = get_app_user_id());
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'conversation_members' AND policyname = 'cm_insert_own') THEN
    CREATE POLICY "cm_insert_own" ON conversation_members FOR INSERT
      WITH CHECK (user_id = get_app_user_id());
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'conversation_members' AND policyname = 'cm_update_own') THEN
    CREATE POLICY "cm_update_own" ON conversation_members FOR UPDATE
      USING (user_id = get_app_user_id());
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'conversations' AND policyname = 'conv_select_member') THEN
    CREATE POLICY "conv_select_member" ON conversations FOR SELECT
      USING (id IN (SELECT conversation_id FROM conversation_members WHERE user_id = get_app_user_id()));
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'conversations' AND policyname = 'conv_insert_auth') THEN
    CREATE POLICY "conv_insert_auth" ON conversations FOR INSERT
      WITH CHECK (auth.uid() IS NOT NULL);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'messages' AND policyname = 'msg_select_member') THEN
    CREATE POLICY "msg_select_member" ON messages FOR SELECT
      USING (conversation_id IN (SELECT conversation_id FROM conversation_members WHERE user_id = get_app_user_id()));
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'messages' AND policyname = 'msg_insert_member') THEN
    CREATE POLICY "msg_insert_member" ON messages FOR INSERT
      WITH CHECK (
        sender_id = get_app_user_id()
        AND conversation_id IN (SELECT conversation_id FROM conversation_members WHERE user_id = get_app_user_id())
      );
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'posts' AND policyname = 'posts_select_auth') THEN
    CREATE POLICY "posts_select_auth" ON posts FOR SELECT USING (auth.uid() IS NOT NULL);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'posts' AND policyname = 'posts_insert_auth') THEN
    CREATE POLICY "posts_insert_auth" ON posts FOR INSERT WITH CHECK (
      author_id = get_app_user_id()
      AND (
        COALESCE(is_urgent, false) = false
        OR EXISTS (
          SELECT 1 FROM team_members tm
          JOIN channels c ON c.team_id = tm.team_id
          WHERE c.id = channel_id AND tm.user_id = get_app_user_id() AND tm.role = 'admin'
        )
      )
    );
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'posts' AND policyname = 'posts_update_own') THEN
    CREATE POLICY "posts_update_own" ON posts FOR UPDATE USING (
      author_id = get_app_user_id()
    );
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'posts' AND policyname = 'posts_delete_own') THEN
    CREATE POLICY "posts_delete_own" ON posts FOR DELETE USING (
      author_id = get_app_user_id()
    );
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'reactions' AND policyname = 'reactions_select_all') THEN
    CREATE POLICY "reactions_select_all" ON reactions FOR SELECT USING (auth.uid() IS NOT NULL);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'reactions' AND policyname = 'reactions_insert_own') THEN
    CREATE POLICY "reactions_insert_own" ON reactions FOR INSERT WITH CHECK (
      user_id = get_app_user_id()
    );
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'reactions' AND policyname = 'reactions_delete_own') THEN
    CREATE POLICY "reactions_delete_own" ON reactions FOR DELETE USING (
      user_id = get_app_user_id()
    );
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'users' AND policyname = 'users_select_auth') THEN
    CREATE POLICY "users_select_auth" ON users FOR SELECT USING (auth.uid() IS NOT NULL);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'users' AND policyname = 'users_update_own') THEN
    CREATE POLICY "users_update_own" ON users FOR UPDATE USING (
      auth_uid = auth.uid()
    ) WITH CHECK (
      auth_uid = auth.uid()
    );
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'team_members' AND policyname = 'tm_select_auth') THEN
    CREATE POLICY "tm_select_auth" ON team_members FOR SELECT USING (auth.uid() IS NOT NULL);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'team_members' AND policyname = 'tm_insert_admin') THEN
    CREATE POLICY "tm_insert_admin" ON team_members FOR INSERT WITH CHECK (
      EXISTS (
        SELECT 1 FROM team_members tm
        WHERE tm.team_id = team_members.team_id
          AND tm.user_id = get_app_user_id()
          AND tm.role = 'admin'
      )
      AND role IN ('member', 'admin')
    );
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'team_members' AND policyname = 'tm_delete_admin') THEN
    CREATE POLICY "tm_delete_admin" ON team_members FOR DELETE USING (
      EXISTS (
        SELECT 1 FROM team_members tm
        WHERE tm.team_id = team_members.team_id
          AND tm.user_id = get_app_user_id()
          AND tm.role = 'admin'
      )
    );
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'teams' AND policyname = 'teams_select_member') THEN
    CREATE POLICY "teams_select_member" ON teams FOR SELECT USING (
      id IN (SELECT team_id FROM team_members WHERE user_id = get_app_user_id())
    );
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'teams' AND policyname = 'teams_insert_auth') THEN
    CREATE POLICY "teams_insert_auth" ON teams FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'channels' AND policyname = 'channels_select_member') THEN
    CREATE POLICY "channels_select_member" ON channels FOR SELECT USING (
      team_id IN (SELECT team_id FROM team_members WHERE user_id = get_app_user_id())
    );
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'post_reads' AND policyname = 'pr_select_auth') THEN
    CREATE POLICY "pr_select_auth" ON post_reads FOR SELECT USING (auth.uid() IS NOT NULL);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'post_reads' AND policyname = 'pr_insert_own') THEN
    CREATE POLICY "pr_insert_own" ON post_reads FOR INSERT WITH CHECK (user_id = get_app_user_id());
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'posts' AND policyname = 'posts_pin_admin_or_author') THEN
    CREATE POLICY "posts_pin_admin_or_author" ON posts FOR UPDATE USING (
      author_id = get_app_user_id()
      OR EXISTS (
        SELECT 1 FROM team_members tm
        JOIN channels c ON c.team_id = tm.team_id
        WHERE c.id = posts.channel_id
          AND tm.user_id = get_app_user_id()
          AND tm.role = 'admin'
      )
    );
  END IF;

END $$;

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('uploads', 'uploads', false, 5242880,
  ARRAY['image/jpeg', 'image/png', 'image/gif', 'image/webp', 'application/pdf',
        'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'application/vnd.ms-excel', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet']
)
ON CONFLICT (id) DO UPDATE SET
  file_size_limit = 5242880,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'objects' AND schemaname = 'storage' AND policyname = 'uploads_select_auth') THEN
    CREATE POLICY "uploads_select_auth" ON storage.objects FOR SELECT
      USING (bucket_id = 'uploads' AND auth.uid() IS NOT NULL);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'objects' AND schemaname = 'storage' AND policyname = 'uploads_insert_auth') THEN
    CREATE POLICY "uploads_insert_auth" ON storage.objects FOR INSERT
      WITH CHECK (bucket_id = 'uploads' AND auth.uid() IS NOT NULL);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'objects' AND schemaname = 'storage' AND policyname = 'uploads_delete_own') THEN
    CREATE POLICY "uploads_delete_own" ON storage.objects FOR DELETE
      USING (bucket_id = 'uploads' AND (storage.foldername(name))[1] = auth.uid()::text);
  END IF;
END $$;

DO $$ BEGIN
  ALTER TABLE reactions ADD CONSTRAINT reactions_emoji_length CHECK (length(emoji) BETWEEN 1 AND 8);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
